// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'profile.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `by_activity`, `chat_mutation`, `command_error`, `contact_view`, `decode_hex`, `event_view`, `hex`, `key_package_view`, `last_event_view`, `notice_view`, `operation_name`, `profile_error`, `progress_view`, `shown`, `view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Whether a profile already lives in this directory. The difference
/// between "no key yet" and "the key is gone" depends on it, and only the
/// second one is a problem.
Future<bool> hasProfile({required String dir}) =>
    ArveilRust.instance.api.crateApiProfileHasProfile(dir: dir);

/// A fresh 32-byte key as 64 hexadecimal characters, from the operating
/// system's generator. Generated here rather than in Dart so the entropy
/// comes from the same source the rest of the client already trusts, and so
/// a failure is a failure rather than a weaker key.
Future<String> generateProfileKey() =>
    ArveilRust.instance.api.crateApiProfileGenerateProfileKey();

/// Open a profile encrypted at rest. The key comes from the platform store,
/// never from this crate and never from the environment.
Future<Profile> openProfile({required String dir, required String key}) =>
    ArveilRust.instance.api.crateApiProfileOpenProfile(dir: dir, key: key);

/// Open a profile with nothing encrypting it. Only a development build has
/// any business calling this, and it has to say so.
Future<Profile> openUnencryptedProfile({required String dir}) =>
    ArveilRust.instance.api.crateApiProfileOpenUnencryptedProfile(dir: dir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>
abstract class Profile implements RustOpaqueInterface {
  Future<String> approvePairing({
    required String bootstrap,
    required String code,
  });

  Future<Uint8List> archiveFile({
    required String groupId,
    required String eventId,
  });

  Future<ArchivePageView> archivePage({
    PlatformInt64? before,
    required int limit,
  });

  Future<void> awaitPairing({
    required String bootstrap,
    required PairingView session,
  });

  Future<void> beginPairing({required String bootstrap});

  Future<void> cancelAttachment({
    required String groupId,
    required String eventId,
  });

  /// False means finalization already committed: resume it, never claim it was undone.
  Future<bool> cancelPairing({required List<int> sessionId});

  Future<KeyPackageSupplyView> checkKeyPackages();

  /// Stop admitting work, wait for what is running and release the
  /// profile. Idempotent, and every later call fails instead of quietly
  /// opening it again.
  Future<void> close();

  /// The user saved the last exported kit and confirmed its key is kept
  /// apart. Read `setup` again for the new kit state.
  Future<void> confirmKitSaved();

  Future<void> confirmPairing({
    required String bootstrap,
    required List<int> sessionId,
    required String verificationCode,
  });

  Future<List<ContactView>> contacts();

  /// The conversation list, as a query that answers from local state,
  /// most recently active first.
  Future<List<ConversationView>> conversations();

  Future<ChatMutationView> createContactConversation({
    required String bootstrap,
    required List<SavedRecipientView> recipients,
  });

  Future<ChatMutationView> createConversation({
    required String bootstrap,
    required List<String> routes,
    required List<String> safetyNumbers,
  });

  /// Create this profile's identity. The first step of enrollment, and
  /// the one that makes a profile more than a directory.
  Future<void> createIdentity();

  Future<DeviceInventoryView> devices();

  /// Creates an identity if needed, then resumes the existing enrollment.
  /// The invitation is hashed by Rust and is never persisted by Flutter.
  Future<void> enroll({required String bootstrap, required String invite});

  Future<ArchiveView> exportArchive();

  Future<Uint8List> exportAttachment({
    required String groupId,
    required String eventId,
  });

  Future<KitView> exportKit();

  /// One page of a conversation, newest page first: pass the previous
  /// page's `next` as `before` to walk backwards. The application caps
  /// the size whatever is asked for.
  Future<HistoryPageView> historyPage({
    required String groupId,
    PlatformInt64? before,
    required int limit,
  });

  Future<ArchiveReceiptView> importArchive({
    required List<int> encrypted,
    required String secret,
  });

  /// Local snapshot only: its timestamp identifies an earlier relay report.
  Future<KeyPackageSupplyView> keyPackageSupply();

  /// Mark a conversation read up to `cursor`, the newest event a screen
  /// showed. Marking twice, late or past the end is harmless.
  Future<ReadMarkerView> markRead({
    required String groupId,
    required PlatformInt64 cursor,
  });

  Future<String> ownRoute();

  Future<List<RoutePreviewView>> previewRoutes({required List<String> routes});

  Future<String> queueAttachment({
    required String groupId,
    required String name,
    required List<int> bytes,
  });

  Future<ChatMutationView> queueMessage({
    required String groupId,
    required String text,
  });

  Future<ContactView> renameContact({
    required String identityId,
    required String name,
  });

  Future<KeyPackageSupplyView> replenishKeyPackages();

  Future<void> restoreKit({
    required String bootstrap,
    required List<int> encrypted,
    required String secret,
  });

  Future<void> resumeAttachment({
    required String bootstrap,
    required String groupId,
    required String eventId,
  });

  Future<void> resumeRecovery();

  /// A later network failure can follow a durable local revocation. Always
  /// query devices again, and resume with sync rather than creating new state.
  Future<void> revokeDevice({
    required String bootstrap,
    required String deviceId,
  });

  Future<ContactView> saveContact({
    required String route,
    required String name,
    String? safetyNumber,
  });

  /// Text messages of one conversation containing `text`, newest first,
  /// ignoring case and accents. Each call reads a bounded number of
  /// events; pass `next` as `before` to keep searching further back.
  Future<HistoryPageView> searchHistory({
    required String groupId,
    required String text,
    PlatformInt64? before,
    required int limit,
  });

  /// Read durable setup state after opening, completing or retrying an
  /// enrollment. Progress events are hints; this is the source of truth.
  Future<SetupView> setup();

  /// Reserve a watcher synchronously before its asynchronous worker starts.
  /// Stopping during dispatch therefore cannot accidentally revive a stream.
  BigInt startWatching();

  /// Stop the stream this profile is feeding, without closing anything
  /// else. Dropping the subscription on the Rust side is what actually
  /// unsubscribes.
  void stopWatching({required BigInt generation});

  Future<SyncView> sync_({required String bootstrap});

  Future<ContactView> verifyContact({
    required String identityId,
    required String safetyNumber,
  });

  /// Watch progress while operations run. The stream ends when the
  /// profile closes or when `stop_watching` is called; a listener should
  /// stop before cancelling, since the stream is closed from this side.
  Stream<ProgressView> watch({required BigInt generation});
}

class ArchiveEntryView {
  final String groupId;
  final String eventId;
  final String kind;
  final String text;
  final PlatformInt64 createdAt;
  final String? fileName;
  final BigInt? fileSize;

  /// The author the archive names, as a local name or short identifier:
  /// the exporting device's claim, not proof. Absent for own records and
  /// for records without an author.
  final String? senderLabel;

  /// Written by this identity, by the archive's account.
  final bool own;

  const ArchiveEntryView({
    required this.groupId,
    required this.eventId,
    required this.kind,
    required this.text,
    required this.createdAt,
    this.fileName,
    this.fileSize,
    this.senderLabel,
    required this.own,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      eventId.hashCode ^
      kind.hashCode ^
      text.hashCode ^
      createdAt.hashCode ^
      fileName.hashCode ^
      fileSize.hashCode ^
      senderLabel.hashCode ^
      own.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveEntryView &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          eventId == other.eventId &&
          kind == other.kind &&
          text == other.text &&
          createdAt == other.createdAt &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          senderLabel == other.senderLabel &&
          own == other.own;
}

class ArchivePageView {
  final List<ArchiveEntryView> entries;
  final PlatformInt64? next;

  const ArchivePageView({required this.entries, this.next});

  @override
  int get hashCode => entries.hashCode ^ next.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchivePageView &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          next == other.next;
}

class ArchiveReceiptView {
  final int imported;
  final int duplicates;

  const ArchiveReceiptView({required this.imported, required this.duplicates});

  @override
  int get hashCode => imported.hashCode ^ duplicates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveReceiptView &&
          runtimeType == other.runtimeType &&
          imported == other.imported &&
          duplicates == other.duplicates;
}

class ArchiveView {
  final Uint8List encrypted;
  final String secret;
  final int records;
  final int files;
  final int unavailableFiles;

  const ArchiveView({
    required this.encrypted,
    required this.secret,
    required this.records,
    required this.files,
    required this.unavailableFiles,
  });

  @override
  int get hashCode =>
      encrypted.hashCode ^
      secret.hashCode ^
      records.hashCode ^
      files.hashCode ^
      unavailableFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveView &&
          runtimeType == other.runtimeType &&
          encrypted == other.encrypted &&
          secret == other.secret &&
          records == other.records &&
          files == other.files &&
          unavailableFiles == other.unavailableFiles;
}

/// One event of a conversation, as a screen shows it.
enum AttachmentStateView {
  pending,
  transferring,
  ready,
  sent,
  cancelled,
  unavailable,
  expired,
  invalid,
  legacy,
}

class AttachmentView {
  final String name;
  final BigInt size;
  final bool outgoing;
  final AttachmentStateView state;
  final BigInt transferred;
  final BigInt total;

  const AttachmentView({
    required this.name,
    required this.size,
    required this.outgoing,
    required this.state,
    required this.transferred,
    required this.total,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      size.hashCode ^
      outgoing.hashCode ^
      state.hashCode ^
      transferred.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentView &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          outgoing == other.outgoing &&
          state == other.state &&
          transferred == other.transferred &&
          total == other.total;
}

/// A committed mutation may carry a later failure. Retry publication with sync,
/// never by creating a second message or conversation.
class ChatMutationView {
  final String groupId;
  final String? eventId;
  final CommandError? warning;

  const ChatMutationView({required this.groupId, this.eventId, this.warning});

  @override
  int get hashCode => groupId.hashCode ^ eventId.hashCode ^ warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMutationView &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          eventId == other.eventId &&
          warning == other.warning;
}

@freezed
sealed class CommandError with _$CommandError implements FrbException {
  const CommandError._();

  /// The profile already has as much work of this kind as it will hold.
  /// Nothing was started, so a caller may retry once something finishes.
  const factory CommandError.busy({
    required String operation,
    required int active,
  }) = CommandError_Busy;

  /// A command failed in a way nobody described and ended this session.
  /// The profile itself is intact: close it and open it again.
  const factory CommandError.panicked({required String operation}) =
      CommandError_Panicked;
  const factory CommandError.transport({
    required String operation,
    required String reason,
  }) = CommandError_Transport;
  const factory CommandError.storage({
    required String operation,
    required String reason,
  }) = CommandError_Storage;
  const factory CommandError.protocol({
    required String operation,
    required String reason,
  }) = CommandError_Protocol;
  const factory CommandError.domain({
    required String operation,
    required String reason,
  }) = CommandError_Domain;
  const factory CommandError.fileSystem({
    required String operation,
    required String reason,
  }) = CommandError_FileSystem;
  const factory CommandError.internal({
    required String operation,
    required String reason,
  }) = CommandError_Internal;
  const factory CommandError.interrupted({required String reason}) =
      CommandError_Interrupted;
}

class ContactDeviceView {
  final String deviceId;
  final bool revoked;

  const ContactDeviceView({required this.deviceId, required this.revoked});

  @override
  int get hashCode => deviceId.hashCode ^ revoked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDeviceView &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          revoked == other.revoked;
}

class ContactView {
  final String identityId;
  final String? name;
  final String label;
  final bool verified;
  final String safetyNumber;
  final List<ContactDeviceView> devices;

  const ContactView({
    required this.identityId,
    this.name,
    required this.label,
    required this.verified,
    required this.safetyNumber,
    required this.devices,
  });

  @override
  int get hashCode =>
      identityId.hashCode ^
      name.hashCode ^
      label.hashCode ^
      verified.hashCode ^
      safetyNumber.hashCode ^
      devices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactView &&
          runtimeType == other.runtimeType &&
          identityId == other.identityId &&
          name == other.name &&
          label == other.label &&
          verified == other.verified &&
          safetyNumber == other.safetyNumber &&
          devices == other.devices;
}

/// One row of the conversation list. The application orders rows by
/// `last_activity`, most recent first.
class ConversationView {
  final String groupId;
  final bool creator;
  final int peerDevices;
  final List<PeerView> peers;
  final int eventCount;
  final LastEventView? lastEvent;

  /// Messages after this device's read marker that someone else wrote.
  final int unread;

  /// Unix seconds of the newest event, or of when this device started
  /// keeping the conversation.
  final PlatformInt64 lastActivity;

  const ConversationView({
    required this.groupId,
    required this.creator,
    required this.peerDevices,
    required this.peers,
    required this.eventCount,
    this.lastEvent,
    required this.unread,
    required this.lastActivity,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      creator.hashCode ^
      peerDevices.hashCode ^
      peers.hashCode ^
      eventCount.hashCode ^
      lastEvent.hashCode ^
      unread.hashCode ^
      lastActivity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationView &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          creator == other.creator &&
          peerDevices == other.peerDevices &&
          peers == other.peers &&
          eventCount == other.eventCount &&
          lastEvent == other.lastEvent &&
          unread == other.unread &&
          lastActivity == other.lastActivity;
}

class DeviceInventoryView {
  final bool administrator;
  final BigInt manifestSequence;
  final int unknownActive;
  final int unknownRevoked;
  final List<ManagedDeviceView> devices;

  const DeviceInventoryView({
    required this.administrator,
    required this.manifestSequence,
    required this.unknownActive,
    required this.unknownRevoked,
    required this.devices,
  });

  @override
  int get hashCode =>
      administrator.hashCode ^
      manifestSequence.hashCode ^
      unknownActive.hashCode ^
      unknownRevoked.hashCode ^
      devices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInventoryView &&
          runtimeType == other.runtimeType &&
          administrator == other.administrator &&
          manifestSequence == other.manifestSequence &&
          unknownActive == other.unknownActive &&
          unknownRevoked == other.unknownRevoked &&
          devices == other.devices;
}

class HistoryEventView {
  /// Position in the conversation. Pass the oldest one back as `before`
  /// to read the page before this one.
  final PlatformInt64 cursor;
  final String eventId;
  final String kind;
  final Uint8List body;
  final AttachmentView? attachment;

  /// Delivery state per mailbox, for events this device sent.
  final List<String> delivery;

  /// Unix seconds when this device recorded the event: arrival for what
  /// it received, creation for what it sent. Not when the sender wrote it.
  final PlatformInt64 createdAt;

  /// Hexadecimal identity that wrote the event, when known.
  final String? senderIdentity;

  /// Local contact name or short identifier of that identity. Absent for
  /// this profile's own events and for senders nobody can name.
  final String? senderLabel;

  /// Written by this identity, from this device or another of its own.
  final bool own;

  /// For a device-change notice, what changed; its author is the sender.
  final NoticeView? notice;

  const HistoryEventView({
    required this.cursor,
    required this.eventId,
    required this.kind,
    required this.body,
    this.attachment,
    required this.delivery,
    required this.createdAt,
    this.senderIdentity,
    this.senderLabel,
    required this.own,
    this.notice,
  });

  @override
  int get hashCode =>
      cursor.hashCode ^
      eventId.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      attachment.hashCode ^
      delivery.hashCode ^
      createdAt.hashCode ^
      senderIdentity.hashCode ^
      senderLabel.hashCode ^
      own.hashCode ^
      notice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryEventView &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          eventId == other.eventId &&
          kind == other.kind &&
          body == other.body &&
          attachment == other.attachment &&
          delivery == other.delivery &&
          createdAt == other.createdAt &&
          senderIdentity == other.senderIdentity &&
          senderLabel == other.senderLabel &&
          own == other.own &&
          notice == other.notice;
}

/// One page, oldest first within the page.
class HistoryPageView {
  final List<HistoryEventView> events;

  /// Cursor for the page before this one; absent at the beginning of the
  /// conversation.
  final PlatformInt64? next;

  const HistoryPageView({required this.events, this.next});

  @override
  int get hashCode => events.hashCode ^ next.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPageView &&
          runtimeType == other.runtimeType &&
          events == other.events &&
          next == other.next;
}

enum KeyPackageLevelView { unknown, empty, low, ready }

class KeyPackageSupplyView {
  final int? available;
  final BigInt? checkedAt;
  final KeyPackageLevelView level;
  final bool publicationPending;
  final int target;

  const KeyPackageSupplyView({
    this.available,
    this.checkedAt,
    required this.level,
    required this.publicationPending,
    required this.target,
  });

  @override
  int get hashCode =>
      available.hashCode ^
      checkedAt.hashCode ^
      level.hashCode ^
      publicationPending.hashCode ^
      target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageSupplyView &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          checkedAt == other.checkedAt &&
          level == other.level &&
          publicationPending == other.publicationPending &&
          target == other.target;
}

class KitView {
  final Uint8List encrypted;
  final String secret;

  const KitView({required this.encrypted, required this.secret});

  @override
  int get hashCode => encrypted.hashCode ^ secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitView &&
          runtimeType == other.runtimeType &&
          encrypted == other.encrypted &&
          secret == other.secret;
}

/// What a conversation row says about its newest event.
class LastEventView {
  /// Position of the event in its conversation, as history reports it.
  final PlatformInt64 cursor;
  final String kind;

  /// The start of a text message on one line, at most `PREVIEW_CHARS`
  /// characters; empty for every other kind.
  final String preview;
  final String? attachmentName;
  final String? senderLabel;
  final bool own;
  final PlatformInt64 createdAt;

  /// Delivery state per mailbox, for events this device sent.
  final List<String> delivery;
  final NoticeView? notice;

  const LastEventView({
    required this.cursor,
    required this.kind,
    required this.preview,
    this.attachmentName,
    this.senderLabel,
    required this.own,
    required this.createdAt,
    required this.delivery,
    this.notice,
  });

  @override
  int get hashCode =>
      cursor.hashCode ^
      kind.hashCode ^
      preview.hashCode ^
      attachmentName.hashCode ^
      senderLabel.hashCode ^
      own.hashCode ^
      createdAt.hashCode ^
      delivery.hashCode ^
      notice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LastEventView &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          kind == other.kind &&
          preview == other.preview &&
          attachmentName == other.attachmentName &&
          senderLabel == other.senderLabel &&
          own == other.own &&
          createdAt == other.createdAt &&
          delivery == other.delivery &&
          notice == other.notice;
}

class ManagedDeviceView {
  final String deviceId;
  final bool current;
  final bool revoked;
  final RevocationProgressView? revocation;

  const ManagedDeviceView({
    required this.deviceId,
    required this.current,
    required this.revoked,
    this.revocation,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      current.hashCode ^
      revoked.hashCode ^
      revocation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManagedDeviceView &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          current == other.current &&
          revoked == other.revoked &&
          revocation == other.revocation;
}

/// A contact's devices changed. Counts only: no device is named.
class NoticeView {
  final int added;
  final int removed;

  const NoticeView({required this.added, required this.removed});

  @override
  int get hashCode => added.hashCode ^ removed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoticeView &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          removed == other.removed;
}

class PairingView {
  final Uint8List sessionId;
  final String code;
  final BigInt expiresAt;
  final String? verificationCode;
  final bool committing;
  final bool expired;

  const PairingView({
    required this.sessionId,
    required this.code,
    required this.expiresAt,
    this.verificationCode,
    required this.committing,
    required this.expired,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      code.hashCode ^
      expiresAt.hashCode ^
      verificationCode.hashCode ^
      committing.hashCode ^
      expired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingView &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          code == other.code &&
          expiresAt == other.expiresAt &&
          verificationCode == other.verificationCode &&
          committing == other.committing &&
          expired == other.expired;
}

class PeerView {
  final String identityId;
  final String deviceId;
  final String label;
  final bool own;
  final bool verified;
  final bool revoked;

  const PeerView({
    required this.identityId,
    required this.deviceId,
    required this.label,
    required this.own,
    required this.verified,
    required this.revoked,
  });

  @override
  int get hashCode =>
      identityId.hashCode ^
      deviceId.hashCode ^
      label.hashCode ^
      own.hashCode ^
      verified.hashCode ^
      revoked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerView &&
          runtimeType == other.runtimeType &&
          identityId == other.identityId &&
          deviceId == other.deviceId &&
          label == other.label &&
          own == other.own &&
          verified == other.verified &&
          revoked == other.revoked;
}

@freezed
sealed class ProfileError with _$ProfileError implements FrbException {
  const ProfileError._();

  /// The key is not 32 bytes as 64 hexadecimal characters.
  const factory ProfileError.badKey() = ProfileError_BadKey;

  /// The system would not produce randomness. Nothing weaker is used in
  /// its place.
  const factory ProfileError.noRandomness() = ProfileError_NoRandomness;

  /// This process already has a session over that profile. Sharing is a
  /// decision of the caller, not an accident of opening twice.
  const factory ProfileError.alreadyOpen({required String path}) =
      ProfileError_AlreadyOpen;

  /// The profile is being closed; opening it again has to wait.
  const factory ProfileError.closing({required String path}) =
      ProfileError_Closing;

  /// Another process holds the profile.
  const factory ProfileError.inUse({required String path}) = ProfileError_InUse;

  /// A newer version of the app wrote this profile. It was left as it
  /// was; updating the app opens it.
  const factory ProfileError.tooNew({
    required String path,
    required int found,
    required int supported,
  }) = ProfileError_TooNew;

  /// The profile exists but did not open: a wrong key looks like this.
  const factory ProfileError.unusable({
    required String path,
    required String reason,
  }) = ProfileError_Unusable;

  /// The directory itself could not be prepared.
  const factory ProfileError.io({
    required String path,
    required String reason,
  }) = ProfileError_Io;
}

@freezed
sealed class ProgressKindView with _$ProgressKindView {
  const ProgressKindView._();

  const factory ProgressKindView.messageQueued({
    required String groupId,
    required String eventId,
  }) = ProgressKindView_MessageQueued;
  const factory ProgressKindView.messageReceived({
    required String groupId,
    required String eventId,
  }) = ProgressKindView_MessageReceived;
  const factory ProgressKindView.envelopesPublished({
    required int count,
    required bool pending,
  }) = ProgressKindView_EnvelopesPublished;
  const factory ProgressKindView.deliveryChanged({
    required String deliveryId,
    required String state,
  }) = ProgressKindView_DeliveryChanged;
  const factory ProgressKindView.fileAnnounced({
    required String groupId,
    required String eventId,
    required String name,
    required BigInt size,
  }) = ProgressKindView_FileAnnounced;
  const factory ProgressKindView.fileTransfer({
    required String name,
    required BigInt offset,
    BigInt? total,
  }) = ProgressKindView_FileTransfer;
  const factory ProgressKindView.fileSaved({required String name}) =
      ProgressKindView_FileSaved;
  const factory ProgressKindView.synced({
    required int fetched,
    required int new_,
    required int acked,
  }) = ProgressKindView_Synced;
  const factory ProgressKindView.pairingChanged({
    required String sessionId,
    required String phase,
  }) = ProgressKindView_PairingChanged;
  const factory ProgressKindView.relayUnavailable({required int pending}) =
      ProgressKindView_RelayUnavailable;
  const factory ProgressKindView.onboarding({required String step}) =
      ProgressKindView_Onboarding;
  const factory ProgressKindView.gap({required int dropped}) =
      ProgressKindView_Gap;
}

/// Progress while an operation runs. A screen may show it; it does not
/// replace the answer the operation returns, and a `gap` means events were
/// missed and the screen should read the state again.
class ProgressView {
  final BigInt sequence;
  final String operation;
  final ProgressKindView kind;

  const ProgressView({
    required this.sequence,
    required this.operation,
    required this.kind,
  });

  @override
  int get hashCode => sequence.hashCode ^ operation.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressView &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          operation == other.operation &&
          kind == other.kind;
}

/// How far a conversation has been read on this device.
class ReadMarkerView {
  final PlatformInt64 cursor;
  final int unread;

  const ReadMarkerView({required this.cursor, required this.unread});

  @override
  int get hashCode => cursor.hashCode ^ unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadMarkerView &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          unread == other.unread;
}

class RevocationProgressView {
  final bool relayPublished;
  final int groupsWaiting;
  final int notificationsPending;
  final int notificationsUnconfirmed;
  final int withoutRoute;

  const RevocationProgressView({
    required this.relayPublished,
    required this.groupsWaiting,
    required this.notificationsPending,
    required this.notificationsUnconfirmed,
    required this.withoutRoute,
  });

  @override
  int get hashCode =>
      relayPublished.hashCode ^
      groupsWaiting.hashCode ^
      notificationsPending.hashCode ^
      notificationsUnconfirmed.hashCode ^
      withoutRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RevocationProgressView &&
          runtimeType == other.runtimeType &&
          relayPublished == other.relayPublished &&
          groupsWaiting == other.groupsWaiting &&
          notificationsPending == other.notificationsPending &&
          notificationsUnconfirmed == other.notificationsUnconfirmed &&
          withoutRoute == other.withoutRoute;
}

class RoutePreviewView {
  final String identityId;
  final String deviceId;
  final String safetyNumber;

  const RoutePreviewView({
    required this.identityId,
    required this.deviceId,
    required this.safetyNumber,
  });

  @override
  int get hashCode =>
      identityId.hashCode ^ deviceId.hashCode ^ safetyNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutePreviewView &&
          runtimeType == other.runtimeType &&
          identityId == other.identityId &&
          deviceId == other.deviceId &&
          safetyNumber == other.safetyNumber;
}

class SavedRecipientView {
  final String identityId;
  final String deviceId;

  const SavedRecipientView({required this.identityId, required this.deviceId});

  @override
  int get hashCode => identityId.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedRecipientView &&
          runtimeType == other.runtimeType &&
          identityId == other.identityId &&
          deviceId == other.deviceId;
}

enum SetupStage {
  new_,
  identityReady,
  redeeming,
  redeemed,
  publishing,
  ready,
  linkedDevice,
  recovering,
}

class SetupView {
  final SetupStage stage;
  final String? identityId;
  final String? bootstrap;
  final bool administrator;
  final bool recoveryWarning;

  /// Unix seconds when the user last confirmed saving an identity kit on
  /// this administration device; absent if never.
  final PlatformInt64? kitSavedAt;

  /// Devices changed after the saved kit was made; a new kit should
  /// replace it.
  final bool kitStale;
  final PairingView? pairing;

  const SetupView({
    required this.stage,
    this.identityId,
    this.bootstrap,
    required this.administrator,
    required this.recoveryWarning,
    this.kitSavedAt,
    required this.kitStale,
    this.pairing,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      identityId.hashCode ^
      bootstrap.hashCode ^
      administrator.hashCode ^
      recoveryWarning.hashCode ^
      kitSavedAt.hashCode ^
      kitStale.hashCode ^
      pairing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetupView &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          identityId == other.identityId &&
          bootstrap == other.bootstrap &&
          administrator == other.administrator &&
          recoveryWarning == other.recoveryWarning &&
          kitSavedAt == other.kitSavedAt &&
          kitStale == other.kitStale &&
          pairing == other.pairing;
}

class SyncView {
  final int processedEnvelopes;

  const SyncView({required this.processedEnvelopes});

  @override
  int get hashCode => processedEnvelopes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncView &&
          runtimeType == other.runtimeType &&
          processedEnvelopes == other.processedEnvelopes;
}
