// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'profile.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `command_error`, `decode_hex`, `event_view`, `hex`, `operation_name`, `profile_error`, `progress_view`, `shown`, `view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Whether a profile already lives in this directory. The difference
/// between "no key yet" and "the key is gone" depends on it, and only the
/// second one is a problem.
Future<bool> hasProfile({required String dir}) =>
    ArveilRust.instance.api.crateApiProfileHasProfile(dir: dir);

/// A fresh 32-byte key as 64 hexadecimal characters, from the operating
/// system's generator. Generated here rather than in Dart so the entropy
/// comes from the same source the rest of the client already trusts, and so
/// a failure is a failure rather than a weaker key.
Future<String> generateProfileKey() =>
    ArveilRust.instance.api.crateApiProfileGenerateProfileKey();

/// Open a profile encrypted at rest. The key comes from the platform store,
/// never from this crate and never from the environment.
Future<Profile> openProfile({required String dir, required String key}) =>
    ArveilRust.instance.api.crateApiProfileOpenProfile(dir: dir, key: key);

/// Open a profile with nothing encrypting it. Only a development build has
/// any business calling this, and it has to say so.
Future<Profile> openUnencryptedProfile({required String dir}) =>
    ArveilRust.instance.api.crateApiProfileOpenUnencryptedProfile(dir: dir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>
abstract class Profile implements RustOpaqueInterface {
  /// Stop admitting work, wait for what is running and release the
  /// profile. Idempotent, and every later call fails instead of quietly
  /// opening it again.
  Future<void> close();

  /// The conversation list, as a query that answers from local state.
  Future<List<ConversationView>> conversations();

  /// Create this profile's identity. The first step of enrollment, and
  /// the one that makes a profile more than a directory.
  Future<void> createIdentity();

  /// One page of a conversation, newest page first: pass the previous
  /// page's `next` as `before` to walk backwards. The application caps
  /// the size whatever is asked for.
  Future<HistoryPageView> historyPage({
    required String groupId,
    PlatformInt64? before,
    required int limit,
  });

  /// Stop the stream this profile is feeding, without closing anything
  /// else. Dropping the subscription on the Rust side is what actually
  /// unsubscribes.
  void stopWatching();

  /// Watch progress while operations run. The stream ends when the
  /// profile closes or when `stop_watching` is called; a listener should
  /// stop before cancelling, since the stream is closed from this side.
  Stream<ProgressView> watch();
}

@freezed
sealed class CommandError with _$CommandError implements FrbException {
  const CommandError._();

  /// The profile already has as much work of this kind as it will hold.
  /// Nothing was started, so a caller may retry once something finishes.
  const factory CommandError.busy({
    required String operation,
    required int active,
  }) = CommandError_Busy;

  /// A command failed in a way nobody described and ended this session.
  /// The profile itself is intact: close it and open it again.
  const factory CommandError.panicked({required String operation}) =
      CommandError_Panicked;
  const factory CommandError.transport({
    required String operation,
    required String reason,
  }) = CommandError_Transport;
  const factory CommandError.storage({
    required String operation,
    required String reason,
  }) = CommandError_Storage;
  const factory CommandError.protocol({
    required String operation,
    required String reason,
  }) = CommandError_Protocol;
  const factory CommandError.domain({
    required String operation,
    required String reason,
  }) = CommandError_Domain;
  const factory CommandError.fileSystem({
    required String operation,
    required String reason,
  }) = CommandError_FileSystem;
  const factory CommandError.internal({
    required String operation,
    required String reason,
  }) = CommandError_Internal;
  const factory CommandError.interrupted({required String reason}) =
      CommandError_Interrupted;
}

/// One row of the conversation list.
class ConversationView {
  final String groupId;
  final bool creator;
  final int peerDevices;
  final int eventCount;

  const ConversationView({
    required this.groupId,
    required this.creator,
    required this.peerDevices,
    required this.eventCount,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      creator.hashCode ^
      peerDevices.hashCode ^
      eventCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationView &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          creator == other.creator &&
          peerDevices == other.peerDevices &&
          eventCount == other.eventCount;
}

/// One event of a conversation, as a screen shows it.
class HistoryEventView {
  /// Position in the conversation. Pass the oldest one back as `before`
  /// to read the page before this one.
  final PlatformInt64 cursor;
  final String eventId;
  final String kind;
  final Uint8List body;

  /// Delivery state per mailbox, for events this device sent.
  final List<String> delivery;

  const HistoryEventView({
    required this.cursor,
    required this.eventId,
    required this.kind,
    required this.body,
    required this.delivery,
  });

  @override
  int get hashCode =>
      cursor.hashCode ^
      eventId.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      delivery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryEventView &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          eventId == other.eventId &&
          kind == other.kind &&
          body == other.body &&
          delivery == other.delivery;
}

/// One page, oldest first within the page.
class HistoryPageView {
  final List<HistoryEventView> events;

  /// Cursor for the page before this one; absent at the beginning of the
  /// conversation.
  final PlatformInt64? next;

  const HistoryPageView({required this.events, this.next});

  @override
  int get hashCode => events.hashCode ^ next.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPageView &&
          runtimeType == other.runtimeType &&
          events == other.events &&
          next == other.next;
}

@freezed
sealed class ProfileError with _$ProfileError implements FrbException {
  const ProfileError._();

  /// The key is not 32 bytes as 64 hexadecimal characters.
  const factory ProfileError.badKey() = ProfileError_BadKey;

  /// The system would not produce randomness. Nothing weaker is used in
  /// its place.
  const factory ProfileError.noRandomness() = ProfileError_NoRandomness;

  /// This process already has a session over that profile. Sharing is a
  /// decision of the caller, not an accident of opening twice.
  const factory ProfileError.alreadyOpen({required String path}) =
      ProfileError_AlreadyOpen;

  /// The profile is being closed; opening it again has to wait.
  const factory ProfileError.closing({required String path}) =
      ProfileError_Closing;

  /// Another process holds the profile.
  const factory ProfileError.inUse({required String path}) = ProfileError_InUse;

  /// The profile exists but did not open: a wrong key looks like this.
  const factory ProfileError.unusable({
    required String path,
    required String reason,
  }) = ProfileError_Unusable;

  /// The directory itself could not be prepared.
  const factory ProfileError.io({
    required String path,
    required String reason,
  }) = ProfileError_Io;
}

@freezed
sealed class ProgressKindView with _$ProgressKindView {
  const ProgressKindView._();

  const factory ProgressKindView.messageQueued({
    required String groupId,
    required String eventId,
  }) = ProgressKindView_MessageQueued;
  const factory ProgressKindView.messageReceived({
    required String groupId,
    required String eventId,
  }) = ProgressKindView_MessageReceived;
  const factory ProgressKindView.envelopesPublished({
    required int count,
    required bool pending,
  }) = ProgressKindView_EnvelopesPublished;
  const factory ProgressKindView.deliveryChanged({
    required String deliveryId,
    required String state,
  }) = ProgressKindView_DeliveryChanged;
  const factory ProgressKindView.fileAnnounced({
    required String groupId,
    required String eventId,
    required String name,
    required BigInt size,
  }) = ProgressKindView_FileAnnounced;
  const factory ProgressKindView.fileTransfer({
    required String name,
    required BigInt offset,
    BigInt? total,
  }) = ProgressKindView_FileTransfer;
  const factory ProgressKindView.fileSaved({required String name}) =
      ProgressKindView_FileSaved;
  const factory ProgressKindView.synced({
    required int fetched,
    required int new_,
    required int acked,
  }) = ProgressKindView_Synced;
  const factory ProgressKindView.pairingChanged({
    required String sessionId,
    required String phase,
  }) = ProgressKindView_PairingChanged;
  const factory ProgressKindView.relayUnavailable({required int pending}) =
      ProgressKindView_RelayUnavailable;
  const factory ProgressKindView.onboarding({required String step}) =
      ProgressKindView_Onboarding;
  const factory ProgressKindView.gap({required int dropped}) =
      ProgressKindView_Gap;
}

/// Progress while an operation runs. A screen may show it; it does not
/// replace the answer the operation returns, and a `gap` means events were
/// missed and the screen should read the state again.
class ProgressView {
  final BigInt sequence;
  final String operation;
  final ProgressKindView kind;

  const ProgressView({
    required this.sequence,
    required this.operation,
    required this.kind,
  });

  @override
  int get hashCode => sequence.hashCode ^ operation.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressView &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          operation == other.operation &&
          kind == other.kind;
}
