// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'profile.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `command_error`, `hex`, `operation_name`, `profile_error`, `shown`, `view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Open a profile encrypted at rest. The key comes from the platform store,
/// never from this crate and never from the environment.
Future<Profile> openProfile({required String dir, required String key}) =>
    ArveilRust.instance.api.crateApiProfileOpenProfile(dir: dir, key: key);

/// Open a profile with nothing encrypting it. Only a development build has
/// any business calling this, and it has to say so.
Future<Profile> openUnencryptedProfile({required String dir}) =>
    ArveilRust.instance.api.crateApiProfileOpenUnencryptedProfile(dir: dir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>
abstract class Profile implements RustOpaqueInterface {
  /// Stop admitting work, wait for what is running and release the
  /// profile. Idempotent, and every later call fails instead of quietly
  /// opening it again.
  Future<void> close();

  /// The conversation list, as a query that answers from local state.
  Future<List<ConversationView>> conversations();
}

@freezed
sealed class CommandError with _$CommandError implements FrbException {
  const CommandError._();

  const factory CommandError.transport({
    required String operation,
    required String reason,
  }) = CommandError_Transport;
  const factory CommandError.storage({
    required String operation,
    required String reason,
  }) = CommandError_Storage;
  const factory CommandError.protocol({
    required String operation,
    required String reason,
  }) = CommandError_Protocol;
  const factory CommandError.domain({
    required String operation,
    required String reason,
  }) = CommandError_Domain;
  const factory CommandError.fileSystem({
    required String operation,
    required String reason,
  }) = CommandError_FileSystem;
  const factory CommandError.internal({
    required String operation,
    required String reason,
  }) = CommandError_Internal;
  const factory CommandError.interrupted({required String reason}) =
      CommandError_Interrupted;
}

/// One row of the conversation list.
class ConversationView {
  final String groupId;
  final bool creator;
  final int peerDevices;
  final int eventCount;

  const ConversationView({
    required this.groupId,
    required this.creator,
    required this.peerDevices,
    required this.eventCount,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      creator.hashCode ^
      peerDevices.hashCode ^
      eventCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationView &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          creator == other.creator &&
          peerDevices == other.peerDevices &&
          eventCount == other.eventCount;
}

@freezed
sealed class ProfileError with _$ProfileError implements FrbException {
  const ProfileError._();

  /// The key is not 32 bytes as 64 hexadecimal characters.
  const factory ProfileError.badKey() = ProfileError_BadKey;

  /// This process already has a session over that profile. Sharing is a
  /// decision of the caller, not an accident of opening twice.
  const factory ProfileError.alreadyOpen({required String path}) =
      ProfileError_AlreadyOpen;

  /// The profile is being closed; opening it again has to wait.
  const factory ProfileError.closing({required String path}) =
      ProfileError_Closing;

  /// Another process holds the profile.
  const factory ProfileError.inUse({required String path}) = ProfileError_InUse;

  /// The profile exists but did not open: a wrong key looks like this.
  const factory ProfileError.unusable({
    required String path,
    required String reason,
  }) = ProfileError_Unusable;

  /// The directory itself could not be prepared.
  const factory ProfileError.io({
    required String path,
    required String reason,
  }) = ProfileError_Io;
}
