// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Whether `signature` is a valid Ed25519 signature by `public_key` over the
/// update domain separator followed by the exact `payload` bytes.
bool verifyUpdateSignature({
  required List<int> payload,
  required List<int> signature,
  required List<int> publicKey,
}) => ArveilRust.instance.api.crateApiUpdatesVerifyUpdateSignature(
  payload: payload,
  signature: signature,
  publicKey: publicKey,
);

/// The domain separator signed ahead of the payload, for the app's tests and
/// the release tooling to check against.
String updateSignatureDomain() =>
    ArveilRust.instance.api.crateApiUpdatesUpdateSignatureDomain();
