// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/profile.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class ArveilRust
    extends BaseEntrypoint<ArveilRustApi, ArveilRustApiImpl, ArveilRustWire> {
  @internal
  static final instance = ArveilRust._();

  ArveilRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    ArveilRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required ArveilRustApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<ArveilRustApiImpl, ArveilRustWire>
  get apiImplConstructor => ArveilRustApiImpl.new;

  @override
  WireConstructor<ArveilRustWire> get wireConstructor =>
      ArveilRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 862794526;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'arveil_flutter',
        ioDirectory: '../../core/crates/arveil-flutter/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class ArveilRustApi extends BaseApi {
  Future<void> crateApiProfileProfileClose({required Profile that});

  Future<List<ConversationView>> crateApiProfileProfileConversations({
    required Profile that,
  });

  Future<void> crateApiProfileProfileCreateIdentity({required Profile that});

  Future<HistoryPageView> crateApiProfileProfileHistoryPage({
    required Profile that,
    required String groupId,
    PlatformInt64? before,
    required int limit,
  });

  void crateApiProfileProfileStopWatching({required Profile that});

  Stream<ProgressView> crateApiProfileProfileWatch({required Profile that});

  Future<String> crateApiProfileGenerateProfileKey();

  Future<bool> crateApiProfileHasProfile({required String dir});

  Future<Profile> crateApiProfileOpenProfile({
    required String dir,
    required String key,
  });

  Future<Profile> crateApiProfileOpenUnencryptedProfile({required String dir});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Profile;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Profile;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ProfilePtr;
}

class ArveilRustApiImpl extends ArveilRustApiImplPlatform
    implements ArveilRustApi {
  ArveilRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiProfileProfileClose({required Profile that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfileProfileCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileCloseConstMeta =>
      const TaskConstMeta(debugName: "Profile_close", argNames: ["that"]);

  @override
  Future<List<ConversationView>> crateApiProfileProfileConversations({
    required Profile that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation_view,
          decodeErrorData: sse_decode_command_error,
        ),
        constMeta: kCrateApiProfileProfileConversationsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_conversations",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiProfileProfileCreateIdentity({required Profile that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_command_error,
        ),
        constMeta: kCrateApiProfileProfileCreateIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileCreateIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_create_identity",
        argNames: ["that"],
      );

  @override
  Future<HistoryPageView> crateApiProfileProfileHistoryPage({
    required Profile that,
    required String groupId,
    PlatformInt64? before,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_opt_box_autoadd_i_64(before, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_history_page_view,
          decodeErrorData: sse_decode_command_error,
        ),
        constMeta: kCrateApiProfileProfileHistoryPageConstMeta,
        argValues: [that, groupId, before, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileHistoryPageConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_history_page",
        argNames: ["that", "groupId", "before", "limit"],
      );

  @override
  void crateApiProfileProfileStopWatching({required Profile that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfileProfileStopWatchingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileStopWatchingConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_stop_watching",
        argNames: ["that"],
      );

  @override
  Stream<ProgressView> crateApiProfileProfileWatch({required Profile that}) {
    final sink = RustStreamSink<ProgressView>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
              that,
              serializer,
            );
            sse_encode_StreamSink_progress_view_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiProfileProfileWatchConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiProfileProfileWatchConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_watch",
        argNames: ["that", "sink"],
      );

  @override
  Future<String> crateApiProfileGenerateProfileKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_profile_error,
        ),
        constMeta: kCrateApiProfileGenerateProfileKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileGenerateProfileKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_profile_key", argNames: []);

  @override
  Future<bool> crateApiProfileHasProfile({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfileHasProfileConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileHasProfileConstMeta =>
      const TaskConstMeta(debugName: "has_profile", argNames: ["dir"]);

  @override
  Future<Profile> crateApiProfileOpenProfile({
    required String dir,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile,
          decodeErrorData: sse_decode_profile_error,
        ),
        constMeta: kCrateApiProfileOpenProfileConstMeta,
        argValues: [dir, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileOpenProfileConstMeta =>
      const TaskConstMeta(debugName: "open_profile", argNames: ["dir", "key"]);

  @override
  Future<Profile> crateApiProfileOpenUnencryptedProfile({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile,
          decodeErrorData: sse_decode_profile_error,
        ),
        constMeta: kCrateApiProfileOpenUnencryptedProfileConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileOpenUnencryptedProfileConstMeta =>
      const TaskConstMeta(
        debugName: "open_unencrypted_profile",
        argNames: ["dir"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Profile => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Profile => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Profile
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProfileImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Profile
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProfileImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Profile
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProfileImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<ProgressView> dco_decode_StreamSink_progress_view_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CommandError dco_decode_command_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CommandError_Busy(
          operation: dco_decode_String(raw[1]),
          active: dco_decode_u_32(raw[2]),
        );
      case 1:
        return CommandError_Panicked(operation: dco_decode_String(raw[1]));
      case 2:
        return CommandError_Transport(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 3:
        return CommandError_Storage(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 4:
        return CommandError_Protocol(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 5:
        return CommandError_Domain(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 6:
        return CommandError_FileSystem(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 7:
        return CommandError_Internal(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 8:
        return CommandError_Interrupted(reason: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ConversationView dco_decode_conversation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ConversationView(
      groupId: dco_decode_String(arr[0]),
      creator: dco_decode_bool(arr[1]),
      peerDevices: dco_decode_u_32(arr[2]),
      eventCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  HistoryEventView dco_decode_history_event_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return HistoryEventView(
      cursor: dco_decode_i_64(arr[0]),
      eventId: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      body: dco_decode_list_prim_u_8_strict(arr[3]),
      delivery: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  HistoryPageView dco_decode_history_page_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HistoryPageView(
      events: dco_decode_list_history_event_view(arr[0]),
      next: dco_decode_opt_box_autoadd_i_64(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConversationView> dco_decode_list_conversation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation_view).toList();
  }

  @protected
  List<HistoryEventView> dco_decode_list_history_event_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_event_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  ProfileError dco_decode_profile_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ProfileError_BadKey();
      case 1:
        return ProfileError_NoRandomness();
      case 2:
        return ProfileError_AlreadyOpen(path: dco_decode_String(raw[1]));
      case 3:
        return ProfileError_Closing(path: dco_decode_String(raw[1]));
      case 4:
        return ProfileError_InUse(path: dco_decode_String(raw[1]));
      case 5:
        return ProfileError_Unusable(
          path: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 6:
        return ProfileError_Io(
          path: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ProgressKindView dco_decode_progress_kind_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ProgressKindView_MessageQueued(
          groupId: dco_decode_String(raw[1]),
          eventId: dco_decode_String(raw[2]),
        );
      case 1:
        return ProgressKindView_MessageReceived(
          groupId: dco_decode_String(raw[1]),
          eventId: dco_decode_String(raw[2]),
        );
      case 2:
        return ProgressKindView_EnvelopesPublished(
          count: dco_decode_u_32(raw[1]),
          pending: dco_decode_bool(raw[2]),
        );
      case 3:
        return ProgressKindView_DeliveryChanged(
          deliveryId: dco_decode_String(raw[1]),
          state: dco_decode_String(raw[2]),
        );
      case 4:
        return ProgressKindView_FileAnnounced(
          groupId: dco_decode_String(raw[1]),
          eventId: dco_decode_String(raw[2]),
          name: dco_decode_String(raw[3]),
          size: dco_decode_u_64(raw[4]),
        );
      case 5:
        return ProgressKindView_FileTransfer(
          name: dco_decode_String(raw[1]),
          offset: dco_decode_u_64(raw[2]),
          total: dco_decode_opt_box_autoadd_u_64(raw[3]),
        );
      case 6:
        return ProgressKindView_FileSaved(name: dco_decode_String(raw[1]));
      case 7:
        return ProgressKindView_Synced(
          fetched: dco_decode_u_32(raw[1]),
          new_: dco_decode_u_32(raw[2]),
          acked: dco_decode_u_32(raw[3]),
        );
      case 8:
        return ProgressKindView_PairingChanged(
          sessionId: dco_decode_String(raw[1]),
          phase: dco_decode_String(raw[2]),
        );
      case 9:
        return ProgressKindView_RelayUnavailable(
          pending: dco_decode_u_32(raw[1]),
        );
      case 10:
        return ProgressKindView_Onboarding(step: dco_decode_String(raw[1]));
      case 11:
        return ProgressKindView_Gap(dropped: dco_decode_u_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ProgressView dco_decode_progress_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProgressView(
      sequence: dco_decode_u_64(arr[0]),
      operation: dco_decode_String(arr[1]),
      kind: dco_decode_progress_kind_view(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Profile
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProfileImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Profile
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProfileImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Profile
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProfileImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<ProgressView> sse_decode_StreamSink_progress_view_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CommandError sse_decode_command_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_operation = sse_decode_String(deserializer);
        var var_active = sse_decode_u_32(deserializer);
        return CommandError_Busy(operation: var_operation, active: var_active);
      case 1:
        var var_operation = sse_decode_String(deserializer);
        return CommandError_Panicked(operation: var_operation);
      case 2:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Transport(
          operation: var_operation,
          reason: var_reason,
        );
      case 3:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Storage(
          operation: var_operation,
          reason: var_reason,
        );
      case 4:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Protocol(
          operation: var_operation,
          reason: var_reason,
        );
      case 5:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Domain(
          operation: var_operation,
          reason: var_reason,
        );
      case 6:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_FileSystem(
          operation: var_operation,
          reason: var_reason,
        );
      case 7:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Internal(
          operation: var_operation,
          reason: var_reason,
        );
      case 8:
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Interrupted(reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ConversationView sse_decode_conversation_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_String(deserializer);
    var var_creator = sse_decode_bool(deserializer);
    var var_peerDevices = sse_decode_u_32(deserializer);
    var var_eventCount = sse_decode_u_32(deserializer);
    return ConversationView(
      groupId: var_groupId,
      creator: var_creator,
      peerDevices: var_peerDevices,
      eventCount: var_eventCount,
    );
  }

  @protected
  HistoryEventView sse_decode_history_event_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cursor = sse_decode_i_64(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    var var_delivery = sse_decode_list_String(deserializer);
    return HistoryEventView(
      cursor: var_cursor,
      eventId: var_eventId,
      kind: var_kind,
      body: var_body,
      delivery: var_delivery,
    );
  }

  @protected
  HistoryPageView sse_decode_history_page_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_events = sse_decode_list_history_event_view(deserializer);
    var var_next = sse_decode_opt_box_autoadd_i_64(deserializer);
    return HistoryPageView(events: var_events, next: var_next);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversationView> sse_decode_list_conversation_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryEventView> sse_decode_list_history_event_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryEventView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_event_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileError sse_decode_profile_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ProfileError_BadKey();
      case 1:
        return ProfileError_NoRandomness();
      case 2:
        var var_path = sse_decode_String(deserializer);
        return ProfileError_AlreadyOpen(path: var_path);
      case 3:
        var var_path = sse_decode_String(deserializer);
        return ProfileError_Closing(path: var_path);
      case 4:
        var var_path = sse_decode_String(deserializer);
        return ProfileError_InUse(path: var_path);
      case 5:
        var var_path = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return ProfileError_Unusable(path: var_path, reason: var_reason);
      case 6:
        var var_path = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return ProfileError_Io(path: var_path, reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ProgressKindView sse_decode_progress_kind_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_groupId = sse_decode_String(deserializer);
        var var_eventId = sse_decode_String(deserializer);
        return ProgressKindView_MessageQueued(
          groupId: var_groupId,
          eventId: var_eventId,
        );
      case 1:
        var var_groupId = sse_decode_String(deserializer);
        var var_eventId = sse_decode_String(deserializer);
        return ProgressKindView_MessageReceived(
          groupId: var_groupId,
          eventId: var_eventId,
        );
      case 2:
        var var_count = sse_decode_u_32(deserializer);
        var var_pending = sse_decode_bool(deserializer);
        return ProgressKindView_EnvelopesPublished(
          count: var_count,
          pending: var_pending,
        );
      case 3:
        var var_deliveryId = sse_decode_String(deserializer);
        var var_state = sse_decode_String(deserializer);
        return ProgressKindView_DeliveryChanged(
          deliveryId: var_deliveryId,
          state: var_state,
        );
      case 4:
        var var_groupId = sse_decode_String(deserializer);
        var var_eventId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_size = sse_decode_u_64(deserializer);
        return ProgressKindView_FileAnnounced(
          groupId: var_groupId,
          eventId: var_eventId,
          name: var_name,
          size: var_size,
        );
      case 5:
        var var_name = sse_decode_String(deserializer);
        var var_offset = sse_decode_u_64(deserializer);
        var var_total = sse_decode_opt_box_autoadd_u_64(deserializer);
        return ProgressKindView_FileTransfer(
          name: var_name,
          offset: var_offset,
          total: var_total,
        );
      case 6:
        var var_name = sse_decode_String(deserializer);
        return ProgressKindView_FileSaved(name: var_name);
      case 7:
        var var_fetched = sse_decode_u_32(deserializer);
        var var_new_ = sse_decode_u_32(deserializer);
        var var_acked = sse_decode_u_32(deserializer);
        return ProgressKindView_Synced(
          fetched: var_fetched,
          new_: var_new_,
          acked: var_acked,
        );
      case 8:
        var var_sessionId = sse_decode_String(deserializer);
        var var_phase = sse_decode_String(deserializer);
        return ProgressKindView_PairingChanged(
          sessionId: var_sessionId,
          phase: var_phase,
        );
      case 9:
        var var_pending = sse_decode_u_32(deserializer);
        return ProgressKindView_RelayUnavailable(pending: var_pending);
      case 10:
        var var_step = sse_decode_String(deserializer);
        return ProgressKindView_Onboarding(step: var_step);
      case 11:
        var var_dropped = sse_decode_u_32(deserializer);
        return ProgressKindView_Gap(dropped: var_dropped);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ProgressView sse_decode_progress_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sequence = sse_decode_u_64(deserializer);
    var var_operation = sse_decode_String(deserializer);
    var var_kind = sse_decode_progress_kind_view(deserializer);
    return ProgressView(
      sequence: var_sequence,
      operation: var_operation,
      kind: var_kind,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProfileImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProfileImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProfileImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_progress_view_Sse(
    RustStreamSink<ProgressView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_command_error(CommandError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CommandError_Busy(operation: final operation, active: final active):
        sse_encode_i_32(0, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_u_32(active, serializer);
      case CommandError_Panicked(operation: final operation):
        sse_encode_i_32(1, serializer);
        sse_encode_String(operation, serializer);
      case CommandError_Transport(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Storage(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Protocol(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Domain(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_FileSystem(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Internal(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(7, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Interrupted(reason: final reason):
        sse_encode_i_32(8, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_conversation_view(
    ConversationView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.groupId, serializer);
    sse_encode_bool(self.creator, serializer);
    sse_encode_u_32(self.peerDevices, serializer);
    sse_encode_u_32(self.eventCount, serializer);
  }

  @protected
  void sse_encode_history_event_view(
    HistoryEventView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.cursor, serializer);
    sse_encode_String(self.eventId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_list_prim_u_8_strict(self.body, serializer);
    sse_encode_list_String(self.delivery, serializer);
  }

  @protected
  void sse_encode_history_page_view(
    HistoryPageView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_history_event_view(self.events, serializer);
    sse_encode_opt_box_autoadd_i_64(self.next, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation_view(
    List<ConversationView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_event_view(
    List<HistoryEventView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_event_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_error(ProfileError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ProfileError_BadKey():
        sse_encode_i_32(0, serializer);
      case ProfileError_NoRandomness():
        sse_encode_i_32(1, serializer);
      case ProfileError_AlreadyOpen(path: final path):
        sse_encode_i_32(2, serializer);
        sse_encode_String(path, serializer);
      case ProfileError_Closing(path: final path):
        sse_encode_i_32(3, serializer);
        sse_encode_String(path, serializer);
      case ProfileError_InUse(path: final path):
        sse_encode_i_32(4, serializer);
        sse_encode_String(path, serializer);
      case ProfileError_Unusable(path: final path, reason: final reason):
        sse_encode_i_32(5, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(reason, serializer);
      case ProfileError_Io(path: final path, reason: final reason):
        sse_encode_i_32(6, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_progress_kind_view(
    ProgressKindView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ProgressKindView_MessageQueued(
        groupId: final groupId,
        eventId: final eventId,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(groupId, serializer);
        sse_encode_String(eventId, serializer);
      case ProgressKindView_MessageReceived(
        groupId: final groupId,
        eventId: final eventId,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(groupId, serializer);
        sse_encode_String(eventId, serializer);
      case ProgressKindView_EnvelopesPublished(
        count: final count,
        pending: final pending,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_u_32(count, serializer);
        sse_encode_bool(pending, serializer);
      case ProgressKindView_DeliveryChanged(
        deliveryId: final deliveryId,
        state: final state,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(deliveryId, serializer);
        sse_encode_String(state, serializer);
      case ProgressKindView_FileAnnounced(
        groupId: final groupId,
        eventId: final eventId,
        name: final name,
        size: final size,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(groupId, serializer);
        sse_encode_String(eventId, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(size, serializer);
      case ProgressKindView_FileTransfer(
        name: final name,
        offset: final offset,
        total: final total,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(offset, serializer);
        sse_encode_opt_box_autoadd_u_64(total, serializer);
      case ProgressKindView_FileSaved(name: final name):
        sse_encode_i_32(6, serializer);
        sse_encode_String(name, serializer);
      case ProgressKindView_Synced(
        fetched: final fetched,
        new_: final new_,
        acked: final acked,
      ):
        sse_encode_i_32(7, serializer);
        sse_encode_u_32(fetched, serializer);
        sse_encode_u_32(new_, serializer);
        sse_encode_u_32(acked, serializer);
      case ProgressKindView_PairingChanged(
        sessionId: final sessionId,
        phase: final phase,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_String(phase, serializer);
      case ProgressKindView_RelayUnavailable(pending: final pending):
        sse_encode_i_32(9, serializer);
        sse_encode_u_32(pending, serializer);
      case ProgressKindView_Onboarding(step: final step):
        sse_encode_i_32(10, serializer);
        sse_encode_String(step, serializer);
      case ProgressKindView_Gap(dropped: final dropped):
        sse_encode_i_32(11, serializer);
        sse_encode_u_32(dropped, serializer);
    }
  }

  @protected
  void sse_encode_progress_view(ProgressView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sequence, serializer);
    sse_encode_String(self.operation, serializer);
    sse_encode_progress_kind_view(self.kind, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ProfileImpl extends RustOpaque implements Profile {
  // Not to be used by end users
  ProfileImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ProfileImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        ArveilRust.instance.api.rust_arc_increment_strong_count_Profile,
    rustArcDecrementStrongCount:
        ArveilRust.instance.api.rust_arc_decrement_strong_count_Profile,
    rustArcDecrementStrongCountPtr:
        ArveilRust.instance.api.rust_arc_decrement_strong_count_ProfilePtr,
  );

  /// Stop admitting work, wait for what is running and release the
  /// profile. Idempotent, and every later call fails instead of quietly
  /// opening it again.
  Future<void> close() =>
      ArveilRust.instance.api.crateApiProfileProfileClose(that: this);

  /// The conversation list, as a query that answers from local state.
  Future<List<ConversationView>> conversations() =>
      ArveilRust.instance.api.crateApiProfileProfileConversations(that: this);

  /// Create this profile's identity. The first step of enrollment, and
  /// the one that makes a profile more than a directory.
  Future<void> createIdentity() =>
      ArveilRust.instance.api.crateApiProfileProfileCreateIdentity(that: this);

  /// One page of a conversation, newest page first: pass the previous
  /// page's `next` as `before` to walk backwards. The application caps
  /// the size whatever is asked for.
  Future<HistoryPageView> historyPage({
    required String groupId,
    PlatformInt64? before,
    required int limit,
  }) => ArveilRust.instance.api.crateApiProfileProfileHistoryPage(
    that: this,
    groupId: groupId,
    before: before,
    limit: limit,
  );

  /// Stop the stream this profile is feeding, without closing anything
  /// else. Dropping the subscription on the Rust side is what actually
  /// unsubscribes.
  void stopWatching() =>
      ArveilRust.instance.api.crateApiProfileProfileStopWatching(that: this);

  /// Watch progress while operations run. The stream ends when the
  /// profile closes or when `stop_watching` is called; a listener should
  /// stop before cancelling, since the stream is closed from this side.
  Stream<ProgressView> watch() =>
      ArveilRust.instance.api.crateApiProfileProfileWatch(that: this);
}
