// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/profile.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class ArveilRustApiImplPlatform extends BaseApiImpl<ArveilRustWire> {
  ArveilRustApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ProfilePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Profile
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  );

  @protected
  Profile
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  );

  @protected
  Profile
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProgressView> dco_decode_StreamSink_progress_view_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AttachmentStateView dco_decode_attachment_state_view(dynamic raw);

  @protected
  AttachmentView dco_decode_attachment_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AttachmentView dco_decode_box_autoadd_attachment_view(dynamic raw);

  @protected
  CommandError dco_decode_box_autoadd_command_error(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  PairingView dco_decode_box_autoadd_pairing_view(dynamic raw);

  @protected
  RevocationProgressView dco_decode_box_autoadd_revocation_progress_view(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ChatMutationView dco_decode_chat_mutation_view(dynamic raw);

  @protected
  CommandError dco_decode_command_error(dynamic raw);

  @protected
  ContactDeviceView dco_decode_contact_device_view(dynamic raw);

  @protected
  ContactView dco_decode_contact_view(dynamic raw);

  @protected
  ConversationView dco_decode_conversation_view(dynamic raw);

  @protected
  DeviceInventoryView dco_decode_device_inventory_view(dynamic raw);

  @protected
  HistoryEventView dco_decode_history_event_view(dynamic raw);

  @protected
  HistoryPageView dco_decode_history_page_view(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyPackageLevelView dco_decode_key_package_level_view(dynamic raw);

  @protected
  KeyPackageSupplyView dco_decode_key_package_supply_view(dynamic raw);

  @protected
  KitView dco_decode_kit_view(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ContactDeviceView> dco_decode_list_contact_device_view(dynamic raw);

  @protected
  List<ContactView> dco_decode_list_contact_view(dynamic raw);

  @protected
  List<ConversationView> dco_decode_list_conversation_view(dynamic raw);

  @protected
  List<HistoryEventView> dco_decode_list_history_event_view(dynamic raw);

  @protected
  List<ManagedDeviceView> dco_decode_list_managed_device_view(dynamic raw);

  @protected
  List<PeerView> dco_decode_list_peer_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoutePreviewView> dco_decode_list_route_preview_view(dynamic raw);

  @protected
  List<SavedRecipientView> dco_decode_list_saved_recipient_view(dynamic raw);

  @protected
  ManagedDeviceView dco_decode_managed_device_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AttachmentView? dco_decode_opt_box_autoadd_attachment_view(dynamic raw);

  @protected
  CommandError? dco_decode_opt_box_autoadd_command_error(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PairingView? dco_decode_opt_box_autoadd_pairing_view(dynamic raw);

  @protected
  RevocationProgressView? dco_decode_opt_box_autoadd_revocation_progress_view(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PairingView dco_decode_pairing_view(dynamic raw);

  @protected
  PeerView dco_decode_peer_view(dynamic raw);

  @protected
  ProfileError dco_decode_profile_error(dynamic raw);

  @protected
  ProgressKindView dco_decode_progress_kind_view(dynamic raw);

  @protected
  ProgressView dco_decode_progress_view(dynamic raw);

  @protected
  RevocationProgressView dco_decode_revocation_progress_view(dynamic raw);

  @protected
  RoutePreviewView dco_decode_route_preview_view(dynamic raw);

  @protected
  SavedRecipientView dco_decode_saved_recipient_view(dynamic raw);

  @protected
  SetupStage dco_decode_setup_stage(dynamic raw);

  @protected
  SetupView dco_decode_setup_view(dynamic raw);

  @protected
  SyncView dco_decode_sync_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Profile
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  );

  @protected
  Profile
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  );

  @protected
  Profile
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProgressView> sse_decode_StreamSink_progress_view_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AttachmentStateView sse_decode_attachment_state_view(
    SseDeserializer deserializer,
  );

  @protected
  AttachmentView sse_decode_attachment_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AttachmentView sse_decode_box_autoadd_attachment_view(
    SseDeserializer deserializer,
  );

  @protected
  CommandError sse_decode_box_autoadd_command_error(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PairingView sse_decode_box_autoadd_pairing_view(SseDeserializer deserializer);

  @protected
  RevocationProgressView sse_decode_box_autoadd_revocation_progress_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ChatMutationView sse_decode_chat_mutation_view(SseDeserializer deserializer);

  @protected
  CommandError sse_decode_command_error(SseDeserializer deserializer);

  @protected
  ContactDeviceView sse_decode_contact_device_view(
    SseDeserializer deserializer,
  );

  @protected
  ContactView sse_decode_contact_view(SseDeserializer deserializer);

  @protected
  ConversationView sse_decode_conversation_view(SseDeserializer deserializer);

  @protected
  DeviceInventoryView sse_decode_device_inventory_view(
    SseDeserializer deserializer,
  );

  @protected
  HistoryEventView sse_decode_history_event_view(SseDeserializer deserializer);

  @protected
  HistoryPageView sse_decode_history_page_view(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyPackageLevelView sse_decode_key_package_level_view(
    SseDeserializer deserializer,
  );

  @protected
  KeyPackageSupplyView sse_decode_key_package_supply_view(
    SseDeserializer deserializer,
  );

  @protected
  KitView sse_decode_kit_view(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ContactDeviceView> sse_decode_list_contact_device_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ContactView> sse_decode_list_contact_view(SseDeserializer deserializer);

  @protected
  List<ConversationView> sse_decode_list_conversation_view(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryEventView> sse_decode_list_history_event_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ManagedDeviceView> sse_decode_list_managed_device_view(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerView> sse_decode_list_peer_view(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoutePreviewView> sse_decode_list_route_preview_view(
    SseDeserializer deserializer,
  );

  @protected
  List<SavedRecipientView> sse_decode_list_saved_recipient_view(
    SseDeserializer deserializer,
  );

  @protected
  ManagedDeviceView sse_decode_managed_device_view(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AttachmentView? sse_decode_opt_box_autoadd_attachment_view(
    SseDeserializer deserializer,
  );

  @protected
  CommandError? sse_decode_opt_box_autoadd_command_error(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PairingView? sse_decode_opt_box_autoadd_pairing_view(
    SseDeserializer deserializer,
  );

  @protected
  RevocationProgressView? sse_decode_opt_box_autoadd_revocation_progress_view(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PairingView sse_decode_pairing_view(SseDeserializer deserializer);

  @protected
  PeerView sse_decode_peer_view(SseDeserializer deserializer);

  @protected
  ProfileError sse_decode_profile_error(SseDeserializer deserializer);

  @protected
  ProgressKindView sse_decode_progress_kind_view(SseDeserializer deserializer);

  @protected
  ProgressView sse_decode_progress_view(SseDeserializer deserializer);

  @protected
  RevocationProgressView sse_decode_revocation_progress_view(
    SseDeserializer deserializer,
  );

  @protected
  RoutePreviewView sse_decode_route_preview_view(SseDeserializer deserializer);

  @protected
  SavedRecipientView sse_decode_saved_recipient_view(
    SseDeserializer deserializer,
  );

  @protected
  SetupStage sse_decode_setup_stage(SseDeserializer deserializer);

  @protected
  SetupView sse_decode_setup_view(SseDeserializer deserializer);

  @protected
  SyncView sse_decode_sync_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_view_Sse(
    RustStreamSink<ProgressView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_state_view(
    AttachmentStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_attachment_view(
    AttachmentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_attachment_view(
    AttachmentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_command_error(
    CommandError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pairing_view(
    PairingView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_revocation_progress_view(
    RevocationProgressView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_chat_mutation_view(
    ChatMutationView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_command_error(CommandError self, SseSerializer serializer);

  @protected
  void sse_encode_contact_device_view(
    ContactDeviceView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_view(ContactView self, SseSerializer serializer);

  @protected
  void sse_encode_conversation_view(
    ConversationView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_inventory_view(
    DeviceInventoryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_event_view(
    HistoryEventView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_page_view(
    HistoryPageView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_package_level_view(
    KeyPackageLevelView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_package_supply_view(
    KeyPackageSupplyView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_kit_view(KitView self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact_device_view(
    List<ContactDeviceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_contact_view(
    List<ContactView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_view(
    List<ConversationView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_event_view(
    List<HistoryEventView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_managed_device_view(
    List<ManagedDeviceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_view(List<PeerView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_route_preview_view(
    List<RoutePreviewView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_recipient_view(
    List<SavedRecipientView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_managed_device_view(
    ManagedDeviceView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_attachment_view(
    AttachmentView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_command_error(
    CommandError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pairing_view(
    PairingView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_revocation_progress_view(
    RevocationProgressView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_view(PairingView self, SseSerializer serializer);

  @protected
  void sse_encode_peer_view(PeerView self, SseSerializer serializer);

  @protected
  void sse_encode_profile_error(ProfileError self, SseSerializer serializer);

  @protected
  void sse_encode_progress_kind_view(
    ProgressKindView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_progress_view(ProgressView self, SseSerializer serializer);

  @protected
  void sse_encode_revocation_progress_view(
    RevocationProgressView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_route_preview_view(
    RoutePreviewView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_saved_recipient_view(
    SavedRecipientView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_setup_stage(SetupStage self, SseSerializer serializer);

  @protected
  void sse_encode_setup_view(SetupView self, SseSerializer serializer);

  @protected
  void sse_encode_sync_view(SyncView self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class ArveilRustWire implements BaseWire {
  ArveilRustWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
        ptr,
      );
}

@JS('wasm_bindgen')
external ArveilRustWasmModule get wasmModule;

@JS()
@anonymous
extension type ArveilRustWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    int ptr,
  );
}
