// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/profile.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class ArveilRust
    extends BaseEntrypoint<ArveilRustApi, ArveilRustApiImpl, ArveilRustWire> {
  @internal
  static final instance = ArveilRust._();

  ArveilRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    ArveilRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required ArveilRustApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<ArveilRustApiImpl, ArveilRustWire>
  get apiImplConstructor => ArveilRustApiImpl.new;

  @override
  WireConstructor<ArveilRustWire> get wireConstructor =>
      ArveilRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1365805558;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'arveil_flutter',
        ioDirectory: '../../core/crates/arveil-flutter/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class ArveilRustApi extends BaseApi {
  Future<void> crateApiProfileProfileClose({required Profile that});

  Future<List<ConversationView>> crateApiProfileProfileConversations({
    required Profile that,
  });

  Future<HistoryPageView> crateApiProfileProfileHistoryPage({
    required Profile that,
    required String groupId,
    PlatformInt64? before,
    required int limit,
  });

  Future<Profile> crateApiProfileOpenProfile({
    required String dir,
    required String key,
  });

  Future<Profile> crateApiProfileOpenUnencryptedProfile({required String dir});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Profile;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Profile;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ProfilePtr;
}

class ArveilRustApiImpl extends ArveilRustApiImplPlatform
    implements ArveilRustApi {
  ArveilRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiProfileProfileClose({required Profile that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfileProfileCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileCloseConstMeta =>
      const TaskConstMeta(debugName: "Profile_close", argNames: ["that"]);

  @override
  Future<List<ConversationView>> crateApiProfileProfileConversations({
    required Profile that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation_view,
          decodeErrorData: sse_decode_command_error,
        ),
        constMeta: kCrateApiProfileProfileConversationsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_conversations",
        argNames: ["that"],
      );

  @override
  Future<HistoryPageView> crateApiProfileProfileHistoryPage({
    required Profile that,
    required String groupId,
    PlatformInt64? before,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_opt_box_autoadd_i_64(before, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_history_page_view,
          decodeErrorData: sse_decode_command_error,
        ),
        constMeta: kCrateApiProfileProfileHistoryPageConstMeta,
        argValues: [that, groupId, before, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileHistoryPageConstMeta =>
      const TaskConstMeta(
        debugName: "Profile_history_page",
        argNames: ["that", "groupId", "before", "limit"],
      );

  @override
  Future<Profile> crateApiProfileOpenProfile({
    required String dir,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile,
          decodeErrorData: sse_decode_profile_error,
        ),
        constMeta: kCrateApiProfileOpenProfileConstMeta,
        argValues: [dir, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileOpenProfileConstMeta =>
      const TaskConstMeta(debugName: "open_profile", argNames: ["dir", "key"]);

  @override
  Future<Profile> crateApiProfileOpenUnencryptedProfile({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile,
          decodeErrorData: sse_decode_profile_error,
        ),
        constMeta: kCrateApiProfileOpenUnencryptedProfileConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileOpenUnencryptedProfileConstMeta =>
      const TaskConstMeta(
        debugName: "open_unencrypted_profile",
        argNames: ["dir"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Profile => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Profile => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile;

  @protected
  Profile
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProfileImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Profile
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProfileImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Profile
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProfileImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  CommandError dco_decode_command_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CommandError_Busy(
          operation: dco_decode_String(raw[1]),
          active: dco_decode_u_32(raw[2]),
        );
      case 1:
        return CommandError_Transport(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 2:
        return CommandError_Storage(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 3:
        return CommandError_Protocol(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 4:
        return CommandError_Domain(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 5:
        return CommandError_FileSystem(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 6:
        return CommandError_Internal(
          operation: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 7:
        return CommandError_Interrupted(reason: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ConversationView dco_decode_conversation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ConversationView(
      groupId: dco_decode_String(arr[0]),
      creator: dco_decode_bool(arr[1]),
      peerDevices: dco_decode_u_32(arr[2]),
      eventCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  HistoryEventView dco_decode_history_event_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return HistoryEventView(
      cursor: dco_decode_i_64(arr[0]),
      eventId: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      body: dco_decode_list_prim_u_8_strict(arr[3]),
      delivery: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  HistoryPageView dco_decode_history_page_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HistoryPageView(
      events: dco_decode_list_history_event_view(arr[0]),
      next: dco_decode_opt_box_autoadd_i_64(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConversationView> dco_decode_list_conversation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation_view).toList();
  }

  @protected
  List<HistoryEventView> dco_decode_list_history_event_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_event_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ProfileError dco_decode_profile_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ProfileError_BadKey();
      case 1:
        return ProfileError_AlreadyOpen(path: dco_decode_String(raw[1]));
      case 2:
        return ProfileError_Closing(path: dco_decode_String(raw[1]));
      case 3:
        return ProfileError_InUse(path: dco_decode_String(raw[1]));
      case 4:
        return ProfileError_Unusable(
          path: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 5:
        return ProfileError_Io(
          path: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Profile
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProfileImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Profile
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProfileImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Profile
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProfileImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  CommandError sse_decode_command_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_operation = sse_decode_String(deserializer);
        var var_active = sse_decode_u_32(deserializer);
        return CommandError_Busy(operation: var_operation, active: var_active);
      case 1:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Transport(
          operation: var_operation,
          reason: var_reason,
        );
      case 2:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Storage(
          operation: var_operation,
          reason: var_reason,
        );
      case 3:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Protocol(
          operation: var_operation,
          reason: var_reason,
        );
      case 4:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Domain(
          operation: var_operation,
          reason: var_reason,
        );
      case 5:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_FileSystem(
          operation: var_operation,
          reason: var_reason,
        );
      case 6:
        var var_operation = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Internal(
          operation: var_operation,
          reason: var_reason,
        );
      case 7:
        var var_reason = sse_decode_String(deserializer);
        return CommandError_Interrupted(reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ConversationView sse_decode_conversation_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_String(deserializer);
    var var_creator = sse_decode_bool(deserializer);
    var var_peerDevices = sse_decode_u_32(deserializer);
    var var_eventCount = sse_decode_u_32(deserializer);
    return ConversationView(
      groupId: var_groupId,
      creator: var_creator,
      peerDevices: var_peerDevices,
      eventCount: var_eventCount,
    );
  }

  @protected
  HistoryEventView sse_decode_history_event_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cursor = sse_decode_i_64(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    var var_delivery = sse_decode_list_String(deserializer);
    return HistoryEventView(
      cursor: var_cursor,
      eventId: var_eventId,
      kind: var_kind,
      body: var_body,
      delivery: var_delivery,
    );
  }

  @protected
  HistoryPageView sse_decode_history_page_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_events = sse_decode_list_history_event_view(deserializer);
    var var_next = sse_decode_opt_box_autoadd_i_64(deserializer);
    return HistoryPageView(events: var_events, next: var_next);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversationView> sse_decode_list_conversation_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryEventView> sse_decode_list_history_event_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryEventView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_event_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileError sse_decode_profile_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ProfileError_BadKey();
      case 1:
        var var_path = sse_decode_String(deserializer);
        return ProfileError_AlreadyOpen(path: var_path);
      case 2:
        var var_path = sse_decode_String(deserializer);
        return ProfileError_Closing(path: var_path);
      case 3:
        var var_path = sse_decode_String(deserializer);
        return ProfileError_InUse(path: var_path);
      case 4:
        var var_path = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return ProfileError_Unusable(path: var_path, reason: var_reason);
      case 5:
        var var_path = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return ProfileError_Io(path: var_path, reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProfileImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProfileImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
    Profile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProfileImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_command_error(CommandError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CommandError_Busy(operation: final operation, active: final active):
        sse_encode_i_32(0, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_u_32(active, serializer);
      case CommandError_Transport(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Storage(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Protocol(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Domain(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_FileSystem(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Internal(
        operation: final operation,
        reason: final reason,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(operation, serializer);
        sse_encode_String(reason, serializer);
      case CommandError_Interrupted(reason: final reason):
        sse_encode_i_32(7, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_conversation_view(
    ConversationView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.groupId, serializer);
    sse_encode_bool(self.creator, serializer);
    sse_encode_u_32(self.peerDevices, serializer);
    sse_encode_u_32(self.eventCount, serializer);
  }

  @protected
  void sse_encode_history_event_view(
    HistoryEventView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.cursor, serializer);
    sse_encode_String(self.eventId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_list_prim_u_8_strict(self.body, serializer);
    sse_encode_list_String(self.delivery, serializer);
  }

  @protected
  void sse_encode_history_page_view(
    HistoryPageView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_history_event_view(self.events, serializer);
    sse_encode_opt_box_autoadd_i_64(self.next, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation_view(
    List<ConversationView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_event_view(
    List<HistoryEventView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_event_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_error(ProfileError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ProfileError_BadKey():
        sse_encode_i_32(0, serializer);
      case ProfileError_AlreadyOpen(path: final path):
        sse_encode_i_32(1, serializer);
        sse_encode_String(path, serializer);
      case ProfileError_Closing(path: final path):
        sse_encode_i_32(2, serializer);
        sse_encode_String(path, serializer);
      case ProfileError_InUse(path: final path):
        sse_encode_i_32(3, serializer);
        sse_encode_String(path, serializer);
      case ProfileError_Unusable(path: final path, reason: final reason):
        sse_encode_i_32(4, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(reason, serializer);
      case ProfileError_Io(path: final path, reason: final reason):
        sse_encode_i_32(5, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ProfileImpl extends RustOpaque implements Profile {
  // Not to be used by end users
  ProfileImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ProfileImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        ArveilRust.instance.api.rust_arc_increment_strong_count_Profile,
    rustArcDecrementStrongCount:
        ArveilRust.instance.api.rust_arc_decrement_strong_count_Profile,
    rustArcDecrementStrongCountPtr:
        ArveilRust.instance.api.rust_arc_decrement_strong_count_ProfilePtr,
  );

  /// Stop admitting work, wait for what is running and release the
  /// profile. Idempotent, and every later call fails instead of quietly
  /// opening it again.
  Future<void> close() =>
      ArveilRust.instance.api.crateApiProfileProfileClose(that: this);

  /// The conversation list, as a query that answers from local state.
  Future<List<ConversationView>> conversations() =>
      ArveilRust.instance.api.crateApiProfileProfileConversations(that: this);

  /// One page of a conversation, newest page first: pass the previous
  /// page's `next` as `before` to walk backwards. The application caps
  /// the size whatever is asked for.
  Future<HistoryPageView> historyPage({
    required String groupId,
    PlatformInt64? before,
    required int limit,
  }) => ArveilRust.instance.api.crateApiProfileProfileHistoryPage(
    that: this,
    groupId: groupId,
    before: before,
    limit: limit,
  );
}
