#!/usr/bin/env python3
"""Export committed platform icons from assets/brand (macOS + Python 3)."""

import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "assets/brand"
MAC = ROOT / "clients/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset"
ANDROID = ROOT / "clients/flutter/android/app/src/main/res"


def resize(source: Path, destination: Path, size: int) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["sips", "--resampleHeightWidth", str(size), str(size), str(source),
         "--out", str(destination)],
        check=True, stdout=subprocess.DEVNULL,
    )


def write_resource(relative: str, content: str) -> None:
    path = ANDROID / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    if not shutil.which("sips") or not shutil.which("iconutil"):
        raise SystemExit("Run this export on macOS (sips and iconutil required).")

    # Keep the catalog filenames stable so Xcode consumes these automatically.
    catalog = json.loads((MAC / "Contents.json").read_text())
    for entry in catalog["images"]:
        size = int(entry["size"].split("x")[0]) * int(entry["scale"][0])
        resize(BRAND / "icon-macos-source.png", MAC / entry["filename"], size)

    for density, size in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96),
                          ("xxhdpi", 144), ("xxxhdpi", 192)]:
        resize(BRAND / "icon-square-source.png",
               ANDROID / f"mipmap-{density}/ic_launcher.png", size)

    # A native vector avoids raster fringes in Android's tinted alpha mask.
    mark = ET.parse(BRAND / "mark.svg").getroot().find("{http://www.w3.org/2000/svg}path")
    path_data = mark.attrib["d"]
    vector = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/export_app_icons.py from assets/brand/mark.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="1024" android:viewportHeight="1024">
    <!-- Scale around the center to stay inside the 66dp circular safe zone. -->
    <group android:pivotX="512" android:pivotY="512"
        android:scaleX="0.72" android:scaleY="0.72">
        <path android:fillColor="{mark.attrib['fill']}"
            android:pathData="{path_data}" />
    </group>
</vector>
'''
    write_resource("drawable/ic_launcher_foreground.xml", vector)
    write_resource("values/icon_colors.xml", '''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">#245B51</color>
</resources>
''')
    for api in (26, 33):
        mono = ('    <monochrome android:drawable="@drawable/ic_launcher_foreground" />\n'
                if api >= 33 else "")
        write_resource(f"mipmap-anydpi-v{api}/ic_launcher.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/export_app_icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
{mono}</adaptive-icon>
''')

    # Convenience exports stay out of Git; installers use the catalog/resources.
    output = ROOT / "dist/brand"
    output.mkdir(parents=True, exist_ok=True)
    resize(BRAND / "icon-square-source.png", output / "arveil-1024.png", 1024)
    resize(BRAND / "icon-square-source.png", output / "arveil-512.png", 512)
    with tempfile.TemporaryDirectory() as temporary:
        iconset = Path(temporary) / "Arveil.iconset"
        iconset.mkdir()
        for size in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                suffix = "@2x" if scale == 2 else ""
                shutil.copyfile(MAC / f"app_icon_{size * scale}.png",
                                iconset / f"icon_{size}x{size}{suffix}.png")
        subprocess.run(["iconutil", "--convert", "icns", str(iconset),
                        "--output", str(output / "Arveil.icns")], check=True)
    print("Exported macOS catalog, Android launcher resources and dist/brand extras.")


if __name__ == "__main__":
    main()
