// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use crate::api::profile::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1655380575;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__profile__Profile_close_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "Profile_close",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Ok::<_, ()>({
                        crate::api::profile::Profile::close(&*api_that_guard);
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__profile__Profile_conversations_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "Profile_conversations",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::profile::CommandError>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = crate::api::profile::Profile::conversations(&*api_that_guard)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__profile__Profile_create_identity_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "Profile_create_identity",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::profile::CommandError>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok =
                        crate::api::profile::Profile::create_identity(&*api_that_guard)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__profile__Profile_history_page_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "Profile_history_page",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
            >>::sse_decode(&mut deserializer);
            let api_group_id = <String>::sse_decode(&mut deserializer);
            let api_before = <Option<i64>>::sse_decode(&mut deserializer);
            let api_limit = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::profile::CommandError>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = crate::api::profile::Profile::history_page(
                        &*api_that_guard,
                        api_group_id,
                        api_before,
                        api_limit,
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__profile__Profile_stop_watching_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "Profile_stop_watching",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok = Ok::<_, ()>({
                    crate::api::profile::Profile::stop_watching(&*api_that_guard);
                })?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__profile__Profile_watch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "Profile_watch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
            >>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::profile::ProgressView,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Ok::<_, ()>({
                        crate::api::profile::Profile::watch(&*api_that_guard, api_sink);
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__profile__open_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_dir = <String>::sse_decode(&mut deserializer);
            let api_key = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::profile::ProfileError>((move || {
                    let output_ok = crate::api::profile::open_profile(api_dir, api_key)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__profile__open_unencrypted_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_unencrypted_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::profile::ProfileError>((move || {
                    let output_ok = crate::api::profile::open_unencrypted_profile(api_dir)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>
);

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for Profile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::profile::ProgressView, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::profile::CommandError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_active = <u32>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Busy {
                    operation: var_operation,
                    active: var_active,
                };
            }
            1 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Transport {
                    operation: var_operation,
                    reason: var_reason,
                };
            }
            2 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Storage {
                    operation: var_operation,
                    reason: var_reason,
                };
            }
            3 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Protocol {
                    operation: var_operation,
                    reason: var_reason,
                };
            }
            4 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Domain {
                    operation: var_operation,
                    reason: var_reason,
                };
            }
            5 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::FileSystem {
                    operation: var_operation,
                    reason: var_reason,
                };
            }
            6 => {
                let mut var_operation = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Internal {
                    operation: var_operation,
                    reason: var_reason,
                };
            }
            7 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::CommandError::Interrupted { reason: var_reason };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::profile::ConversationView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_groupId = <String>::sse_decode(deserializer);
        let mut var_creator = <bool>::sse_decode(deserializer);
        let mut var_peerDevices = <u32>::sse_decode(deserializer);
        let mut var_eventCount = <u32>::sse_decode(deserializer);
        return crate::api::profile::ConversationView {
            group_id: var_groupId,
            creator: var_creator,
            peer_devices: var_peerDevices,
            event_count: var_eventCount,
        };
    }
}

impl SseDecode for crate::api::profile::HistoryEventView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_cursor = <i64>::sse_decode(deserializer);
        let mut var_eventId = <String>::sse_decode(deserializer);
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_body = <Vec<u8>>::sse_decode(deserializer);
        let mut var_delivery = <Vec<String>>::sse_decode(deserializer);
        return crate::api::profile::HistoryEventView {
            cursor: var_cursor,
            event_id: var_eventId,
            kind: var_kind,
            body: var_body,
            delivery: var_delivery,
        };
    }
}

impl SseDecode for crate::api::profile::HistoryPageView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_events = <Vec<crate::api::profile::HistoryEventView>>::sse_decode(deserializer);
        let mut var_next = <Option<i64>>::sse_decode(deserializer);
        return crate::api::profile::HistoryPageView {
            events: var_events,
            next: var_next,
        };
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::profile::ConversationView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::profile::ConversationView>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::profile::HistoryEventView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::profile::HistoryEventView>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::profile::ProfileError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::profile::ProfileError::BadKey;
            }
            1 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::profile::ProfileError::AlreadyOpen { path: var_path };
            }
            2 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::profile::ProfileError::Closing { path: var_path };
            }
            3 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::profile::ProfileError::InUse { path: var_path };
            }
            4 => {
                let mut var_path = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::ProfileError::Unusable {
                    path: var_path,
                    reason: var_reason,
                };
            }
            5 => {
                let mut var_path = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::profile::ProfileError::Io {
                    path: var_path,
                    reason: var_reason,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::profile::ProgressKindView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_groupId = <String>::sse_decode(deserializer);
                let mut var_eventId = <String>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::MessageQueued {
                    group_id: var_groupId,
                    event_id: var_eventId,
                };
            }
            1 => {
                let mut var_groupId = <String>::sse_decode(deserializer);
                let mut var_eventId = <String>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::MessageReceived {
                    group_id: var_groupId,
                    event_id: var_eventId,
                };
            }
            2 => {
                let mut var_count = <u32>::sse_decode(deserializer);
                let mut var_pending = <bool>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::EnvelopesPublished {
                    count: var_count,
                    pending: var_pending,
                };
            }
            3 => {
                let mut var_deliveryId = <String>::sse_decode(deserializer);
                let mut var_state = <String>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::DeliveryChanged {
                    delivery_id: var_deliveryId,
                    state: var_state,
                };
            }
            4 => {
                let mut var_groupId = <String>::sse_decode(deserializer);
                let mut var_eventId = <String>::sse_decode(deserializer);
                let mut var_name = <String>::sse_decode(deserializer);
                let mut var_size = <u64>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::FileAnnounced {
                    group_id: var_groupId,
                    event_id: var_eventId,
                    name: var_name,
                    size: var_size,
                };
            }
            5 => {
                let mut var_name = <String>::sse_decode(deserializer);
                let mut var_offset = <u64>::sse_decode(deserializer);
                let mut var_total = <Option<u64>>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::FileTransfer {
                    name: var_name,
                    offset: var_offset,
                    total: var_total,
                };
            }
            6 => {
                let mut var_name = <String>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::FileSaved { name: var_name };
            }
            7 => {
                let mut var_fetched = <u32>::sse_decode(deserializer);
                let mut var_new_ = <u32>::sse_decode(deserializer);
                let mut var_acked = <u32>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::Synced {
                    fetched: var_fetched,
                    new: var_new_,
                    acked: var_acked,
                };
            }
            8 => {
                let mut var_sessionId = <String>::sse_decode(deserializer);
                let mut var_phase = <String>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::PairingChanged {
                    session_id: var_sessionId,
                    phase: var_phase,
                };
            }
            9 => {
                let mut var_pending = <u32>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::RelayUnavailable {
                    pending: var_pending,
                };
            }
            10 => {
                let mut var_step = <String>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::Onboarding { step: var_step };
            }
            11 => {
                let mut var_dropped = <u32>::sse_decode(deserializer);
                return crate::api::profile::ProgressKindView::Gap {
                    dropped: var_dropped,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::profile::ProgressView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sequence = <u64>::sse_decode(deserializer);
        let mut var_operation = <String>::sse_decode(deserializer);
        let mut var_kind = <crate::api::profile::ProgressKindView>::sse_decode(deserializer);
        return crate::api::profile::ProgressView {
            sequence: var_sequence,
            operation: var_operation,
            kind: var_kind,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__profile__Profile_close_impl(port, ptr, rust_vec_len, data_len),
        2 => {
            wire__crate__api__profile__Profile_conversations_impl(port, ptr, rust_vec_len, data_len)
        }
        3 => wire__crate__api__profile__Profile_create_identity_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => {
            wire__crate__api__profile__Profile_history_page_impl(port, ptr, rust_vec_len, data_len)
        }
        6 => wire__crate__api__profile__Profile_watch_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__profile__open_profile_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__profile__open_unencrypted_profile_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        5 => wire__crate__api__profile__Profile_stop_watching_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<Profile> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<Profile> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<Profile>> for Profile {
    fn into_into_dart(self) -> FrbWrapper<Profile> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::CommandError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::profile::CommandError::Busy { operation, active } => [
                0.into_dart(),
                operation.into_into_dart().into_dart(),
                active.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::Transport { operation, reason } => [
                1.into_dart(),
                operation.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::Storage { operation, reason } => [
                2.into_dart(),
                operation.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::Protocol { operation, reason } => [
                3.into_dart(),
                operation.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::Domain { operation, reason } => [
                4.into_dart(),
                operation.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::FileSystem { operation, reason } => [
                5.into_dart(),
                operation.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::Internal { operation, reason } => [
                6.into_dart(),
                operation.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::CommandError::Interrupted { reason } => {
                [7.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::CommandError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::CommandError>
    for crate::api::profile::CommandError
{
    fn into_into_dart(self) -> crate::api::profile::CommandError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::ConversationView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.group_id.into_into_dart().into_dart(),
            self.creator.into_into_dart().into_dart(),
            self.peer_devices.into_into_dart().into_dart(),
            self.event_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::ConversationView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::ConversationView>
    for crate::api::profile::ConversationView
{
    fn into_into_dart(self) -> crate::api::profile::ConversationView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::HistoryEventView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.cursor.into_into_dart().into_dart(),
            self.event_id.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.body.into_into_dart().into_dart(),
            self.delivery.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::HistoryEventView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::HistoryEventView>
    for crate::api::profile::HistoryEventView
{
    fn into_into_dart(self) -> crate::api::profile::HistoryEventView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::HistoryPageView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.events.into_into_dart().into_dart(),
            self.next.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::HistoryPageView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::HistoryPageView>
    for crate::api::profile::HistoryPageView
{
    fn into_into_dart(self) -> crate::api::profile::HistoryPageView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::ProfileError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::profile::ProfileError::BadKey => [0.into_dart()].into_dart(),
            crate::api::profile::ProfileError::AlreadyOpen { path } => {
                [1.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::profile::ProfileError::Closing { path } => {
                [2.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::profile::ProfileError::InUse { path } => {
                [3.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::profile::ProfileError::Unusable { path, reason } => [
                4.into_dart(),
                path.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProfileError::Io { path, reason } => [
                5.into_dart(),
                path.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::ProfileError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::ProfileError>
    for crate::api::profile::ProfileError
{
    fn into_into_dart(self) -> crate::api::profile::ProfileError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::ProgressKindView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::profile::ProgressKindView::MessageQueued { group_id, event_id } => [
                0.into_dart(),
                group_id.into_into_dart().into_dart(),
                event_id.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::MessageReceived { group_id, event_id } => [
                1.into_dart(),
                group_id.into_into_dart().into_dart(),
                event_id.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::EnvelopesPublished { count, pending } => [
                2.into_dart(),
                count.into_into_dart().into_dart(),
                pending.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::DeliveryChanged { delivery_id, state } => [
                3.into_dart(),
                delivery_id.into_into_dart().into_dart(),
                state.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::FileAnnounced {
                group_id,
                event_id,
                name,
                size,
            } => [
                4.into_dart(),
                group_id.into_into_dart().into_dart(),
                event_id.into_into_dart().into_dart(),
                name.into_into_dart().into_dart(),
                size.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::FileTransfer {
                name,
                offset,
                total,
            } => [
                5.into_dart(),
                name.into_into_dart().into_dart(),
                offset.into_into_dart().into_dart(),
                total.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::FileSaved { name } => {
                [6.into_dart(), name.into_into_dart().into_dart()].into_dart()
            }
            crate::api::profile::ProgressKindView::Synced {
                fetched,
                new,
                acked,
            } => [
                7.into_dart(),
                fetched.into_into_dart().into_dart(),
                new.into_into_dart().into_dart(),
                acked.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::PairingChanged { session_id, phase } => [
                8.into_dart(),
                session_id.into_into_dart().into_dart(),
                phase.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::profile::ProgressKindView::RelayUnavailable { pending } => {
                [9.into_dart(), pending.into_into_dart().into_dart()].into_dart()
            }
            crate::api::profile::ProgressKindView::Onboarding { step } => {
                [10.into_dart(), step.into_into_dart().into_dart()].into_dart()
            }
            crate::api::profile::ProgressKindView::Gap { dropped } => {
                [11.into_dart(), dropped.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::ProgressKindView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::ProgressKindView>
    for crate::api::profile::ProgressKindView
{
    fn into_into_dart(self) -> crate::api::profile::ProgressKindView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::profile::ProgressView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sequence.into_into_dart().into_dart(),
            self.operation.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::profile::ProgressView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::profile::ProgressView>
    for crate::api::profile::ProgressView
{
    fn into_into_dart(self) -> crate::api::profile::ProgressView {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for Profile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::profile::ProgressView, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::profile::CommandError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::profile::CommandError::Busy { operation, active } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(operation, serializer);
                <u32>::sse_encode(active, serializer);
            }
            crate::api::profile::CommandError::Transport { operation, reason } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(operation, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::CommandError::Storage { operation, reason } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(operation, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::CommandError::Protocol { operation, reason } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(operation, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::CommandError::Domain { operation, reason } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(operation, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::CommandError::FileSystem { operation, reason } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(operation, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::CommandError::Internal { operation, reason } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(operation, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::CommandError::Interrupted { reason } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(reason, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::profile::ConversationView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.group_id, serializer);
        <bool>::sse_encode(self.creator, serializer);
        <u32>::sse_encode(self.peer_devices, serializer);
        <u32>::sse_encode(self.event_count, serializer);
    }
}

impl SseEncode for crate::api::profile::HistoryEventView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.cursor, serializer);
        <String>::sse_encode(self.event_id, serializer);
        <String>::sse_encode(self.kind, serializer);
        <Vec<u8>>::sse_encode(self.body, serializer);
        <Vec<String>>::sse_encode(self.delivery, serializer);
    }
}

impl SseEncode for crate::api::profile::HistoryPageView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::profile::HistoryEventView>>::sse_encode(self.events, serializer);
        <Option<i64>>::sse_encode(self.next, serializer);
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::profile::ConversationView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::profile::ConversationView>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::profile::HistoryEventView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::profile::HistoryEventView>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::profile::ProfileError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::profile::ProfileError::BadKey => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::profile::ProfileError::AlreadyOpen { path } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::profile::ProfileError::Closing { path } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::profile::ProfileError::InUse { path } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::profile::ProfileError::Unusable { path, reason } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(path, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::profile::ProfileError::Io { path, reason } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(path, serializer);
                <String>::sse_encode(reason, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::profile::ProgressKindView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::profile::ProgressKindView::MessageQueued { group_id, event_id } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(group_id, serializer);
                <String>::sse_encode(event_id, serializer);
            }
            crate::api::profile::ProgressKindView::MessageReceived { group_id, event_id } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(group_id, serializer);
                <String>::sse_encode(event_id, serializer);
            }
            crate::api::profile::ProgressKindView::EnvelopesPublished { count, pending } => {
                <i32>::sse_encode(2, serializer);
                <u32>::sse_encode(count, serializer);
                <bool>::sse_encode(pending, serializer);
            }
            crate::api::profile::ProgressKindView::DeliveryChanged { delivery_id, state } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(delivery_id, serializer);
                <String>::sse_encode(state, serializer);
            }
            crate::api::profile::ProgressKindView::FileAnnounced {
                group_id,
                event_id,
                name,
                size,
            } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(group_id, serializer);
                <String>::sse_encode(event_id, serializer);
                <String>::sse_encode(name, serializer);
                <u64>::sse_encode(size, serializer);
            }
            crate::api::profile::ProgressKindView::FileTransfer {
                name,
                offset,
                total,
            } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(name, serializer);
                <u64>::sse_encode(offset, serializer);
                <Option<u64>>::sse_encode(total, serializer);
            }
            crate::api::profile::ProgressKindView::FileSaved { name } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(name, serializer);
            }
            crate::api::profile::ProgressKindView::Synced {
                fetched,
                new,
                acked,
            } => {
                <i32>::sse_encode(7, serializer);
                <u32>::sse_encode(fetched, serializer);
                <u32>::sse_encode(new, serializer);
                <u32>::sse_encode(acked, serializer);
            }
            crate::api::profile::ProgressKindView::PairingChanged { session_id, phase } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(session_id, serializer);
                <String>::sse_encode(phase, serializer);
            }
            crate::api::profile::ProgressKindView::RelayUnavailable { pending } => {
                <i32>::sse_encode(9, serializer);
                <u32>::sse_encode(pending, serializer);
            }
            crate::api::profile::ProgressKindView::Onboarding { step } => {
                <i32>::sse_encode(10, serializer);
                <String>::sse_encode(step, serializer);
            }
            crate::api::profile::ProgressKindView::Gap { dropped } => {
                <i32>::sse_encode(11, serializer);
                <u32>::sse_encode(dropped, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::profile::ProgressView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.sequence, serializer);
        <String>::sse_encode(self.operation, serializer);
        <crate::api::profile::ProgressKindView>::sse_encode(self.kind, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use crate::api::profile::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_arveil_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_arveil_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use crate::api::profile::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProfile(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Profile>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
